/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/office-chair.gltf --transform 
Files: public/models/office-chair.gltf [23.17KB] > /Users/johnmiicheal/Documents/git/ojami/client/office-chair-transformed.glb [917.06KB] (-3858%)
Author: sui (https://sketchfab.com/jjosh.wwashington)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/office-chair-5cd859cd7b9a430db0195af2ba89949b
Title: Office Chair
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/office-chair-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube__0.geometry} material={materials['Scene_-_Root']} position={[0, 0.098, 0]} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/office-chair-transformed.glb')
