/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/models/sofa.gltf --transform 
Files: public/models/sofa.gltf [35.97KB] > /Users/johnmiicheal/Documents/git/ojami/client/sofa-transformed.glb [257.2KB] (-615%)
Author: worknworkstudios (https://sketchfab.com/worknworkstudios)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/sofa-game-ready-model-35ea1bdd827a487b96cf60a9b81beaa3
Title: Sofa - Game Ready Model
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/sofa-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube_Fabric_42_0.geometry} material={materials.Fabric_42} position={[0, 0.256, 0.023]} rotation={[-Math.PI / 2, 0, 0]} scale={[1, 0.942, 1]} />
      <mesh geometry={nodes.Cube009_Stylised_wood_0.geometry} material={materials.Stylised_wood} position={[-6.772, -0.448, 2.684]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.252, 0.269, 0.297]} />
    </group>
  )
}

useGLTF.preload('/models/sofa-transformed.glb')
